CREATE TABLE tb_tag(
`tag_id` BIGINT(20) NOT NULL UNSIGNED COMMENT '标签表主键',
`tag_name` VARCHAR(30) NOT NULL COMMENT '标签名',
`tag_bgColor` VARCHAR(15) NOT NULL COMMENT '标签颜色',
`user_id` BIGINT(20) NOT NULL UNSIGNED COMMENT '用户表主键',
PRIMARY KEY (`tag_id`)
)ENGINE=InnoDB AUTO_INCREMENT=2584419330884243457 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT=~'事件表';